name: Test bit7z on macOS with multiple configurations
on: [pull_request, push]

jobs:
  build:
    runs-on: macos-latest
    if: |
      github.event_name == 'pull_request'
      || contains(github.event.head_commit.message, '[test]')
      || startsWith(github.ref, 'refs/tags/v')

    strategy:
      fail-fast: false

      matrix:
        build_type: [Debug, Release]
        bit7z_auto_format: [OFF, ON]
        bit7z_regex_matching: [OFF, ON]
        bit7z_link_libcpp: [OFF, ON]

    steps:
    - uses: actions/checkout@v3

    - name: Building and testing bit7z
      uses: ./.github/actions/test_action
      with:
        c_compiler: clang
        cpp_compiler: clang++
        sevenzip_version: 23.01
        build_type: ${{ matrix.build_type }}
        build_flags: |
            -DBIT7Z_TESTS_USE_SYSTEM_7ZIP=OFF -DBIT7Z_AUTO_FORMAT=${{ matrix.bit7z_auto_format }} -DBIT7Z_REGEX_MATCHING=${{ matrix.bit7z_regex_matching }} -DBIT7Z_LINK_LIBCPP=${{ matrix.bit7z_link_libcpp }}