name: Test bit7z on Ubuntu with multiple configurations
on: [pull_request, push]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request'
      || contains(github.event.head_commit.message, '[test]')
      || contains(github.event.head_commit.message, '[test-linux]')
      || startsWith(github.ref, 'refs/tags/v')

    strategy:
      fail-fast: false

      matrix:
        build_type: [Debug, Release]
        c_compiler: [gcc-9, gcc-10, gcc-11, gcc-12, gcc-13, clang-13, clang-14, clang-15]
        bit7z_auto_format: [OFF, ON]
        bit7z_regex_matching: [OFF, ON]
        bit7z_link_libcpp: [OFF, ON]
        bit7z_7zip_version: [22.01, 23.01]
        include:
          - c_compiler: gcc-9
            cpp_compiler: g++-9
            use_system_7zip: OFF
          - c_compiler: gcc-10
            cpp_compiler: g++-10
            use_system_7zip: OFF
          - c_compiler: gcc-11
            cpp_compiler: g++-11
            use_system_7zip: OFF
          - c_compiler: gcc-12
            cpp_compiler: g++-12
            use_system_7zip: OFF
          - c_compiler: gcc-13
            cpp_compiler: g++-13
            use_system_7zip: OFF
          - c_compiler: clang-13
            cpp_compiler: clang++-13
            use_system_7zip: OFF
          - c_compiler: clang-14
            cpp_compiler: clang++-14
            use_system_7zip: OFF
          - c_compiler: clang-15
            cpp_compiler: clang++-15
            use_system_7zip: OFF
        exclude:
          - c_compiler: gcc-9
            bit7z_link_libcpp: ON
          - c_compiler: gcc-10
            bit7z_link_libcpp: ON
          - c_compiler: gcc-11
            bit7z_link_libcpp: ON
          - c_compiler: gcc-12
            bit7z_link_libcpp: ON
          - c_compiler: gcc-13
            bit7z_link_libcpp: ON

    steps:
    - uses: actions/checkout@v3

    - name: Fix missing libc++ and libc++abi packages for clang-13 compiler
      shell: bash
      if: ${{ contains(matrix.c_compiler, 'clang-13') }}
      run: sudo apt-get purge libc++-14-dev libc++abi-14-dev -y && sudo apt-get install libc++-13-dev libc++abi-13-dev -y
      
    - name: Fix missing libc++ and libc++abi packages for clang-15 compiler
      shell: bash
      if: ${{ contains(matrix.c_compiler, 'clang-15') }}
      run: sudo apt-get purge libc++-14-dev libc++abi-14-dev -y && sudo apt-get install libc++-15-dev libc++abi-15-dev -y

    - name: Building and testing bit7z
      uses: ./.github/actions/test_action
      with:
        c_compiler: ${{ matrix.c_compiler }}
        cpp_compiler: ${{ matrix.cpp_compiler }}
        sevenzip_version: ${{ matrix.bit7z_7zip_version }}
        build_type: ${{ matrix.build_type }}
        build_flags: |
            -DBIT7Z_TESTS_USE_SYSTEM_7ZIP=OFF -DBIT7Z_AUTO_FORMAT=${{ matrix.bit7z_auto_format }} -DBIT7Z_REGEX_MATCHING=${{ matrix.bit7z_regex_matching }} -DBIT7Z_LINK_LIBCPP=${{ matrix.bit7z_link_libcpp }}